// cloudinary-rollup-svelte/src/App.svelte
<script>
	import {AdvancedImage, responsive, lazyload, placeholder, accessibility} from '@cloudinary/svelte';
	import {CloudinaryImage} from "@cloudinary/base";
	const img = new CloudinaryImage('sample', {cloudName: 'demo'});
	export let name;
</script>

<main>
	<h1>Hello {name}!</h1>
	<p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
	<AdvancedImage class="image" cldImg={img} plugins={[lazyload(),responsive(), accessibility(), placeholder()]}/>
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>

// cloudinary-react-webpack/src/App.js
import React from "react";
import {CloudinaryImage} from "@cloudinary/base";
import {AdvancedImage, accessibility, lazyload, placeholder, responsive} from "@cloudinary/react";

const App = () => {
  const img = new CloudinaryImage('sample', {cloudName: 'demo'});
  return (
    <AdvancedImage
      cldImg={img}
      plugins={[lazyload(), responsive(), accessibility(), placeholder()]}
      style={{width: "100%"}}
      alt="Sample"
    />
  );
};

export default App;
